### ISSUE TITLE
Import error in executing the app image

### ISSUE THREAD

**Issue by anirban6908** [BlueBrain/RTNeuron#21]
Hey @hernando 
When I try to execute the app Image using `./rtneuron_x86_64.AppImage --app` I am getting this error

ImportError: libturbojpeg.so.0: cannot open shared object file: No such file or directory

Thanks

**Comment by hernando** [comment]
Ignore the monsteer warning, that's irrelevant.
You can try to visualize the examples from here https://github.com/AllenInstitute/sonata/tree/master/examples.
Regarding the OpenGL errors, those ones look more concerning than anything else. Can you tell me which graphics card do you have? From the errors, it looks like an integrated Intel chip. We have tested RTNeuron only with NVidia graphics cards.

**Comment by hernando** [comment]
@anirban6908 Did you have any chance of testing the examples I linked?
By the way, I've uploaded a new AppImage that fixes some issues, I recommend you to download it again.
I'm going to close this issue in the meantime because the problem originally reported is fixed. Feel free to open a new one if necessary.

**Comment by anirban6908** [comment]
Hey @hernando ,
Nope it's crashing when I try to load the sonata examples. Maybe it's the intel graphics card issue as you alluded. I will try the new app image.
Thanks
